//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub mod prelude;

pub mod sys_dict;
pub mod sys_permission;
pub mod sys_role;
pub mod sys_role_permission;
pub mod sys_user;
pub mod sys_user_role;
