//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8
#![allow(unused_imports)]
pub use super::sys_dict::Entity as SysDict;
pub use super::sys_permission::Entity as SysPermission;
pub use super::sys_role::Entity as SysRole;
pub use super::sys_role_permission::Entity as SysRolePermission;
pub use super::sys_user::Entity as SysUser;
pub use super::sys_user_role::Entity as SysUserRole;
