//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_dict")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub type_code: String,
    pub type_name: String,
    pub item_key: String,
    pub item_value: String,
    pub sort: Option<i32>,
    pub disabled: Option<bool>,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub deleted_at: Option<DateTime>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
